app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
# app/config/routing.yml
users:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Controller/UsersController.php"