# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.entity.repository_calculate:
      class: AppBundle\Repository\CalculateRepo
      factory:
               - "@doctrine.orm.entity_manager"
               - getRepository
      arguments:
               - AppBundle\Entity\CalculateResult
  app.service_calculate:
      class: AppBundle\Service\CalculateService
      arguments : ['@app.entity.repository_calculate']
<<<<<<< HEAD
  app.entity.repository_propsal:
=======
  app.entity.repository_proposal:
>>>>>>> ce2a5d6e2921d5a033a76d0f088a885435c6a6de
      class: AppBundle\Repository\ProposalRepo
      factory:
               - "@doctrine.orm.entity_manager"
               - getRepository
      arguments:
               - AppBundle\Entity\Proposal
<<<<<<< HEAD
=======

>>>>>>> ce2a5d6e2921d5a033a76d0f088a885435c6a6de

