# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.entity.repository_calculate:
      class: AppBundle\Repository\CalculateRepo
      factory:
               - "@doctrine.orm.entity_manager"
               - getRepository
      arguments:
               - AppBundle\Entity\CalculateResult
  app.service_calculate:
      class: AppBundle\Service\CalculateService
      arguments : ['@app.entity.repository_calculate']
  app.entity.repository_proposal:
      class: AppBundle\Repository\ProposalRepo
      factory:
               - "@doctrine.orm.entity_manager"
               - getRepository
      arguments:
               - AppBundle\Entity\Proposal

